---
# This playbook contains common plays that will be run on all nodes.

- name: Update apt cache
  apt: 
    update_cache: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install packages 
  apt: 
    state: present
    pkg:
      - unattended-upgrades
      - etckeeper 
- name: Remove unnessary packages
  apt:
    state: absent
    pkg:
      - nano
- name: Update sshd_config
  template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: '0600'
  register: sshdconf

- name: Restart sshd
  systemd:
    name: sshd
    state: restarted
  when: sshdconf.changed
