---
# This playbook contains common plays that will be run on all nodes.

- name: fetching developer pubkey for jitsi packages
  get_url:
    url: https://download.jitsi.org/jitsi-key.gpg.key
    dest: /root/jitsi-key.gpg.key

- name: converting to binary
  command: gpg --batch --yes -o /usr/share/keyrings/jitsi-keyring.gpg --dearmor /root/jitsi-key.gpg.key

- name: adding jitsi packages source
  template:
    src: templates/jitsi-stable_list.j2
    dest: /etc/apt/sources.list.d/jitsi-stable.list
    owner: root
    group: root
    mode: '0644'

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install jitsi packages 
  apt: 
    state: present
    pkg:
      - apt-transport-https
      - nginx
      - dehydrated
      - debconf-utils
  register: services



- name: adding ACME challenge location to nginx default config
  template:
    src: templates/nginx-default.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: '0644'

- name: enable nginx default config via symlink
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded

- name: adding dehytrated domains.txt 
  template:
    src: templates/domains_txt.j2
    dest: /etc/dehydrated/domains.txt
    owner: root
    group: root
    mode: '0644'

- name: check for let's encryptcertificate updates
  command: /bin/bash -c 'dehydrated --accept-terms -c'
  register: letsencryptdomain

- name: adding nginx {{ server.name }} config 
  template:
    src: templates/nginx-site.j2
    dest: /etc/nginx/sites-available/{{ server.name }}.conf
    owner: root
    group: root
    mode: '0644'
  when: letsencryptdomain.changed

- name: enable nginx config via symlink
  file:
    src: /etc/nginx/sites-available/{{ server.name }}.conf
    dest: /etc/nginx/sites-enabled/{{ server.name }}.conf
    state: link
  when: letsencryptdomain.changed

- name: Reload nginx
  systemd:
    name: nginx
    state: reloaded
  when: letsencryptdomain.changed

- name: creating jitsi package default settings file
  template:
    src: templates/jitsi-debconf.j2
    dest: /root/jitsi-debconf
  register: jitsidebconf

- name: apply jitsi package default settings
  command: debconf-set-selections /root/jitsi-debconf
  when: jitsidebconf.changed

- name: Install jitsi packages 
  apt: 
    state: present
    pkg:
      - jitsi-meet 
